### ISSUE TITLE
Bare-metal provisioning

### ISSUE THREAD

**Issue by ionut-maxim** [khuedoan/homelab#14]
Hey, this is just a proposal/question.

Have you considered using [tinkerbell](https://tinkerbell.org) for bare-metal? I like the solution you have right now, but, I was wondering if there is a specific reason you didn't choose any of the existing solutions out there already.

**Comment by khuedoan** [comment]
Yes I did consider other options, but they have the same limitation: requires the PXE server preconfigured.

Let's take [matchbox](https://matchbox.psdn.io) as an example:

- Install Linux on it (probably via a USB)
- Install matchbox on it
- Install something for Terraform state backend like Minio
- Get the matchbox server + Terraform state backend address and the credentials, fill them in to *.tfvars (or export environment variables) to configure the Terraform provider

Only then you can run Terraform apply, meanwhile my setup just need a single `make` command and it will start the ephemeral PXE server, Wake-on-LAN, and wait for the servers to be ready.

I also [experimented with Cluster API (Sidero)](https://github.com/khuedoan/homelab/pull/2), but I haven't been able to automate it to the level that I desired because of some missing features, and I'm still waiting for its prime time to return to it.

**Comment by ionut-maxim** [comment]
Hey, thanks for the response.

I was also looking into `Sidero` but I don't quite like the fact that it needs a `k8s` cluster already running. Ofcourse they have examples of quickly spinning up a local cluster but still.

**Comment by khuedoan** [comment]
Actually it's not that different from my setup, instead of an ephemeral PXE server, you can create an ephemeral cluster like [this](https://github.com/khuedoan/homelab/pull/2/files#diff-72b37b6f46ab047017cbcaefbdcad16eac978a220a427347ee2687710c2e2009R6) and install Sidero components there.

**Comment by ionut-maxim** [comment]
Again, thank you for your answers. Am going to keep a close 👁️ on your repo. Hopefully you reach stable soon 🎉

**Comment by ionut-maxim** [comment]
Ow, I just found out that `longhorn-storage` isn't supported on `tacos` yet.

**Comment by khuedoan** [comment]
yeah you'll need something without iSCSI like Rook. BTW [Mayastor](https://github.com/openebs/mayastor) just released v1.0.0
