### ISSUE TITLE
iso_url and checksum have changed because of Rocky 8.6

### ISSUE THREAD

**Issue by jaycromer** [khuedoan/homelab#62]
### Describe the bug

The iso_url and iso_checksum values defined in https://github.com/khuedoan/homelab/blob/master/metal/roles/pxe_server/defaults/main.yml are no longer valid as Rocky 8.6 is now available.  The link https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.5-x86_64-minimal.iso results in 404.

### To reproduce

1. Fork repository
2. Run make tools, then run make configure providing information specific to your environment, commit changes.
3. Run make tools, then run make to begin deployment process.
4. When attempt is made to fetch Rocky image, playbook errors on not found.

### Expected behavior

Download of Rocky image would be successful and deploy would complete as expected.

### Additional context

I see two potential solutions:

Use newer Rocky 8.6 iso_url and iso_checksum:

iso_url: "https://download.rockylinux.org/pub/rocky/8/isos/x86_64/Rocky-8.6-x86_64-minimal.iso"
iso_checksum: "sha256:a9ece0e810275e881abfd66bb0e59ac05d567a5ec0bc2f108b9a3e90bef5bf94"

or update iso_url and iso_checksum to point to the old Rocky 8.5 iso at it's new location:

iso_url: "https://download.rockylinux.org/pub/rocky/8.5/isos/x86_64/Rocky-8.5-x86_64-minimal.iso"
iso_checksum: "sha256:4eb2ae6b06876205f2209e4504110fe4115b37540c21ecfbbc0ebc11084cb779"

**Comment by khuedoan** [comment]
Thank you a detailed bug report, I had no idea `https://download.rockylinux.org/pub/rocky/8/xxx` is not a permanent link, fixed in https://github.com/khuedoan/homelab/commit/606c7ab46b8e3ee2b3279d7eca4ff6f17fe7a58d (upgraded to 8.6 using the [permanent link](https://download.rockylinux.org/pub/rocky/8.6/isos/x86_64/Rocky-8.6-x86_64-minimal.iso) and new checksum)

This will not occur again when 8.7 is released.
