### ISSUE TITLE
Is there a tutorial to setting this up on VM (Proxmox)

### ISSUE THREAD

**Issue by mozarik** [khuedoan/homelab#75]
I dont see any tutorial to setting this up on VM. Like maybe i need to change some setting ?

**Comment by khuedoan** [comment]
Is the [sandbox](https://homelab.khuedoan.com/installation/sandbox) sufficient for testing?

If not, there's no tutorial yet, but a PR is welcomed, you can put it in `docs/tutorials`. There's a rough guide [here](https://github.com/khuedoan/homelab/issues/57#issuecomment-1085992663) (for RPi, but should be the same for VM).

**Comment by mozarik** [comment]
thank you for responding

Currently i have 3 old laptop that i connected to proxmox as node. I try the sandbox for testing and play with it. But i need it some kind of `production` thingy. So i can use the cloudflare tunnel. 

Will be asked a lot in this issue. if u dont mind. and of course will make some PR about setting it up using proxmox. 

Thank you

**Comment by llajas** [comment]
FWIW - I was able to get this stood-up all through Hyper-V (I haven't tried ProxMox or any other hypervisor); I provisioned 4 empty VM's across two separate Windows hosts via Terraform on the same VLAN. Hyper-V is configured on each host to provide a MAC address from a pre-determined pool/range upon creation, but I was able to take it a step further by having the Terraform output the MAC addresses specifically into 'prod.yml' for the metal setup prior to the 'make configure' step.

The only thing I couldn't get was the WoL but that was far from a deal breaker - I just triggered a reboot on all the masters/worker via Powershell once the PxE server came online and each node grabbed the respective bootloader without issue.

The controller/PXE host was also running on one of the Hyper-V hosts as well inside Ubuntu Server. Unfortunately I don't have any form of writeup, but I can say that it is possible to run this entire repo across VM's instead of pure metal, but YMMV with different HV's. 😄

**Comment by khuedoan** [comment]
Kinda late but now I have a staging environment on Proxmox, it works basically the same as bare-metal, you'll need:

- No boot ISO

![image](https://github.com/khuedoan/homelab/assets/27996771/ade3d695-a947-4349-a7e9-bc72efe1a251)

- Set BIOS to UEFI (and disable _Add EFI Disk_)

![image](https://github.com/khuedoan/homelab/assets/27996771/dee717ff-a647-460e-b8e9-aecdc13f54a8)

- Use bridge network the VMs can get their IP addresses from LAN (I _think_ this is the default in Proxmox)

![image](https://github.com/khuedoan/homelab/assets/27996771/d29bed70-9987-4334-807f-11027c381725)

As @llajas mentioned we can't use WoL in Proxmox, you'll need to turn them on manually.

I don't use this in my "production" environment so it's unlikely that I'll maintain documentation for it, but an article in `./docs/how-to-guides/` is welcomed 😄
